apiVersion: v1
kind: Service
metadata:
  namespace: odidev
  name: falcon-hbs
  labels:
    app: odidev
spec:
  type: ClusterIP
  ports:
    - name: rpc
      port: 6030
    - name: http
      port: 6031
  selector:
    name: falcon-hbs
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: odidev
  name: falcon-hbs
  labels:
    app: odidev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: falcon-hbs
    spec:
      containers:
        - name: falcon-hbs
          image: registry.cn-hangzhou.aliyuncs.com/odidev/hbs:v0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6030
              name: rpc
              protocol: TCP
            - containerPort: 6031
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /odidev/hbs/config
              name: falcon-hbs-config
            - mountPath: /etc/localtime
              name: tz-config
      volumes:
        - flexVolume:
            driver: alicloud/nas
            options:
              path: /odidev/falcon-hbs/config
              server: xxx.cn-hangzhou.nas.aliyuncs.com
              vers: "4.0"
          name: falcon-hbs-config
        - hostPath:
            path: /etc/localtime
            type: ''
          name: tz-config